# network can be: "BA", "lattice", "minimal" or "random"
network: 'minimal'
# model can be: "SIS",
model: 'SIS'
# plot can be any number. 0 = false, 1 = true
plot: 1
# iteration cannot be 0 or lower
iteration: 10
# keep can either be 1 or 0 depending on the keeping of the save network or not
keep: 0
# mode can be either "dynamic" or "single" depending on the study you want
mode: 'dynamic'
parameters:
  # range must be in the form <deb>-<end> for the range of the parameters. <end> should be bigger than <deb>
  range: "0-1"
  # step is the step of evolution in the range, it should devide <end> - <deb>
  step: 0.1
  # method can be either 'delta' or 'final'
  method: 'final'
